package rdb

var RootRdbUrl string = "https://github.com/libretro/libretro-database/raw/master/rdb/"

var RBDNames = []string{
	"Amstrad - CPC.rdb",
	"Amstrad - GX4000.rdb",
	"Arduboy Inc - Arduboy.rdb",
	"Atari - 2600.rdb",
	"Atari - 5200.rdb",
	"Atari - 7800.rdb",
	"Atari - 8-bit.rdb",
	"Atari - Jaguar.rdb",
	"Atari - Lynx.rdb",
	"Atari - ST.rdb",
	"Atomiswave.rdb",
	"Bandai - WonderSwan Color.rdb",
	"Bandai - WonderSwan.rdb",
	"CHIP-8.rdb",
	"Cannonball.rdb",
	"Casio - Loopy.rdb",
	"Casio - PV-1000.rdb",
	"Cave Story.rdb",
	"ChaiLove.rdb",
	"Coleco - ColecoVision.rdb",
	"Commodore - 64.rdb",
	"Commodore - Amiga.rdb",
	"Commodore - CD32.rdb",
	"Commodore - CDTV.rdb",
	"Commodore - PET.rdb",
	"Commodore - Plus-4.rdb",
	"Commodore - VIC-20.rdb",
	"DICE.rdb",
	"DOOM.rdb",
	"DOS.rdb",
	"Dinothawr.rdb",
	"Emerson - Arcadia 2001.rdb",
	"Enterprise - 128.rdb",
	"Entex - Adventure Vision.rdb",
	"Epoch - Super Cassette Vision.rdb",
	"FBNeo - Arcade Games.rdb",
	"Fairchild - Channel F.rdb",
	"Flashback.rdb",
	"Funtech - Super Acan.rdb",
	"GCE - Vectrex.rdb",
	"GamePark - GP32.rdb",
	"HBMAME.rdb",
	"Handheld Electronic Game.rdb",
	"Hartung - Game Master.rdb",
	"Infocom - Z-Machine.rdb",
	"Jump 'n Bump.rdb",
	"LeapFrog - Leapster Learning Game System.rdb",
	"LowRes NX.rdb",
	"Lutro.rdb",
	//	"MAME 2000.rdb",
	//	"MAME 2003-Plus.rdb",
	//	"MAME 2003.rdb",
	//	"MAME 2010.rdb",
	//	"MAME 2015.rdb",
	//	"MAME 2016.rdb",
	"MAME.rdb",
	"Magnavox - Odyssey2.rdb",
	"Mattel - Intellivision.rdb",
	"MicroW8.rdb",
	"Microsoft - MSX.rdb",
	"Microsoft - MSX2.rdb",
	"Microsoft - Xbox.rdb",
	"Mobile - J2ME.rdb",
	"MrBoom.rdb",
	"NEC - PC Engine - TurboGrafx 16.rdb",
	"NEC - PC Engine CD - TurboGrafx-CD.rdb",
	"NEC - PC Engine SuperGrafx.rdb",
	"NEC - PC-8001 - PC-8801.rdb",
	"NEC - PC-98.rdb",
	"NEC - PC-FX.rdb",
	"Nintendo - Family Computer Disk System.rdb",
	"Nintendo - Game Boy Advance.rdb",
	"Nintendo - Game Boy Color.rdb",
	"Nintendo - Game Boy.rdb",
	"Nintendo - GameCube.rdb",
	"Nintendo - Nintendo 3DS.rdb",
	"Nintendo - Nintendo 64.rdb",
	"Nintendo - Nintendo 64DD.rdb",
	"Nintendo - Nintendo DS.rdb",
	"Nintendo - Nintendo DSi.rdb",
	"Nintendo - Nintendo Entertainment System.rdb",
	"Nintendo - Pokemon Mini.rdb",
	"Nintendo - Satellaview.rdb",
	"Nintendo - Sufami Turbo.rdb",
	"Nintendo - Super Nintendo Entertainment System.rdb",
	"Nintendo - Virtual Boy.rdb",
	"Nintendo - Wii (Digital).rdb",
	"Nintendo - Wii.rdb",
	"Nintendo - e-Reader.rdb",
	"PICO-8.rdb",
	"Philips - CD-i.rdb",
	"Philips - Videopac+.rdb",
	"PuzzleScript.rdb",
	"Quake II.rdb",
	"Quake III.rdb",
	"Quake.rdb",
	"RCA - Studio II.rdb",
	"RPG Maker.rdb",
	"Rick Dangerous.rdb",
	"SNK - Neo Geo CD.rdb",
	"SNK - Neo Geo Pocket Color.rdb",
	"SNK - Neo Geo Pocket.rdb",
	"SNK - Neo Geo.rdb",
	"ScummVM.rdb",
	"Sega - 32X.rdb",
	"Sega - Dreamcast.rdb",
	"Sega - Game Gear.rdb",
	"Sega - Master System - Mark III.rdb",
	"Sega - Mega Drive - Genesis.rdb",
	"Sega - Mega-CD - Sega CD.rdb",
	"Sega - Naomi 2.rdb",
	"Sega - Naomi.rdb",
	"Sega - PICO.rdb",
	"Sega - SG-1000.rdb",
	"Sega - Saturn.rdb",
	"Sharp - X1.rdb",
	"Sharp - X68000.rdb",
	"Sinclair - ZX 81.rdb",
	"Sinclair - ZX Spectrum +3.rdb",
	"Sinclair - ZX Spectrum.rdb",
	"Sony - PlayStation 2.rdb",
	"Sony - PlayStation 3 (PSN).rdb",
	"Sony - PlayStation 3.rdb",
	"Sony - PlayStation Portable (PSN).rdb",
	"Sony - PlayStation Portable.rdb",
	"Sony - PlayStation Vita.rdb",
	"Sony - PlayStation.rdb",
	"Spectravideo - SVI-318 - SVI-328.rdb",
	"TIC-80.rdb",
	"The 3DO Company - 3DO.rdb",
	"Thomson - MOTO.rdb",
	"Tiger - Game.com.rdb",
	"Tomb Raider.rdb",
	"Uzebox.rdb",
	"VTech - CreatiVision.rdb",
	"VTech - V.Smile.rdb",
	"Vircon32.rdb",
	"WASM-4.rdb",
	"Watara - Supervision.rdb",
	"Wolfenstein 3D.rdb",
}
